### ISSUE TITLE
Does it work for antd-mobile?

### ISSUE THREAD

**Issue by zhaoyao91** [DocSpring/craco-antd#13]
Does it work for antd-mobile?

**Comment by ndbroadbent** [comment]
Hello, sorry for the delay, and I didn't know about antd-mobile! 

But I don't think this will work. `craco-antd` depends on the `antd` package. I think you would need to fork `craco-antd` and create a new `craco-antd-mobile` package that depends on `antd-mobile`.

Sorry but I don't use `antd-mobile`, so I do not have time to look into this further.

**Comment by liuliangsir** [comment]
@zhaoyao91 please check out [craco-antd-mobile](https://github.com/w3ctech-editorial-department/craco-antd-mobile).
