### ISSUE TITLE
Need current dependencies for antd and craco

### ISSUE THREAD

**Issue by mbateman-vz** [DocSpring/craco-antd#15]
npm install does not work with current versions of dependencies:
@craco/craco: 5.2.1
antd: 3.19.1
react-scripts: 3.0.1

We get contention on versions of craco by craco-antd and craco-less form react-scripts.

**Comment by ndbroadbent** [comment]
Hello, sorry about that! I have updated everything to the latest versions, and released `craco-antd` version `1.11.0`.

**Comment by mbateman-vz** [comment]
That worked. Thx!
