### ISSUE TITLE
Since version 1.17, only modifyVars allows to modify less variables

### ISSUE THREAD

**Issue by abenhamdine** [DocSpring/craco-antd#39]
Since version 1.17, less variables specified in files antd.customize.json, antd.customize.less or directly in customizeTheme does not seem to work.

Only lessLoaderOptions.modifyVars works.

Tested with craco-antd 1.17, craco-less 1.16, antd 4.3.0

**Comment by ndbroadbent** [comment]
Hello, can you please try updating craco-less to version 1.17? This should resolve the issue since it uses some new loader options

**Comment by ndbroadbent** [comment]
The other option is to downgrade craco-antd to version 1.16

**Comment by abenhamdine** [comment]
> Hello, can you please try updating craco-less to version 1.17? This should resolve the issue since it uses some new loader options

Thx, I will give a try.
But then shouldn't craco-antd be updated to use craco-less 1.17 rather than 1.16 ?

**Comment by ndbroadbent** [comment]
Hello, oh sorry about that, I think it was still using the wrong version of craco-less. Please try craco-antd `1.18.0` and this should be fixed now. Thanks!

**Comment by abenhamdine** [comment]
No problem, and thx a LOT !
