### ISSUE TITLE
craco-less TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by nerdess** [DocSpring/craco-antd#79]
This package has craco-less as dependency. However, depending on the node version I use I get different errors when starting my project using yarn start:

**node v17.3.1**
<img width="608" alt="Bildschirmfoto 2022-01-19 um 09 02 19" src="https://user-images.githubusercontent.com/711925/150091326-b5b35b37-a09c-451f-bebf-acc4292e6e42.png">

**node v14.17.0**
<img width="1518" alt="Bildschirmfoto 2022-01-19 um 09 17 43" src="https://user-images.githubusercontent.com/711925/150091235-5c898d9a-be96-49bf-8809-c9903b728bf4.png">

This is my rather simple **craco.config.js**

    const CracoAntDesignPlugin = require('craco-antd');
    const path = require('path');

    module.exports = {
        webpack: {
		alias: {
			"@components": path.resolve(__dirname, "src/components/"),
			"@util": path.resolve(__dirname, "src/util/"),
			"@pages": path.resolve(__dirname, "src/pages/"),
			"@images": path.resolve(__dirname, "src/images/"),
			"@context": path.resolve(__dirname, "src/context/"),
			"@hooks": path.resolve(__dirname, "src/hooks/"),
		
		},
		plugins: {
			add: [] /* An array of plugins */,
			remove: [] /* An array of plugin constructor's names (i.e. "StyleLintPlugin", "ESLintWebpackPlugin" ) */,
		},
		configure: {
			/* Any webpack configuration options: https://webpack.js.org/configuration */  
		}
	},
	plugins: [
		{
			plugin: CracoAntDesignPlugin,
			options: {
				customizeThemeLessPath: path.join(
					__dirname,
					'./src/antd.customize.less'
				),
			},
		}
	]
};

Any pointers on how to solve this would be great!

**Comment by flyingCrp** [comment]
got the same error in cra5 and croca 
```
"antd": "^4.18.4",
"craco-antd": "^1.19.0",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-scripts": "5.0.0",
```

![image](https://user-images.githubusercontent.com/3668637/150120259-dd9f6ab4-297d-4df0-88ad-65635b1bc88f.png)

**Comment by nerdess** [comment]
@flyingCrp I fixed the issue by removing craco-antd and switching to craco-less. Check out my comment here which also includes my craco.config.js: https://github.com/DocSpring/craco-antd/pull/75

**Comment by flyingCrp** [comment]
> @flyingCrp I fixed the issue by removing craco-antd and switching to craco-less. Check out my comment here which also includes my craco.config.js: #75

yes! thanks for your reply . i got it

**Comment by kamronbatman** [comment]
This is fixed in #75 using my package [@mrbatman/craco-antd](https://www.npmjs.com/package/@mrbatman/craco-antd) if you want to stick to using this package.

**Comment by nerdess** [comment]
@kamronbatman switched back to your version until your PR gets merged. 

One odd thing I noticed: When I change a variable in antd.customize.less and restart my app so that the new variables get picked up they don't. I need to rename the file antd.customize.less into sth else (e.g. antd.customize1.less), change the theme path in craco.config.js to the renamed filename > restart > only _then_ the variables get picked up. It seems like some kind of caching issue (in webpack?? in craco??).

Afaik there is no way in order to pick up changed les variables than to restart the server. But having to also rename the file is really crazy :D Any hints would be cool in case you have the same isssue.

**Comment by kamronbatman** [comment]
I have the same problem. I ended up getting rid of craco-antd and craco-less because I could not find a solution.

**Comment by nerdess** [comment]
@kamronbatman hm, how are you embedding antd in your create-react-app then? afaik antd needs less for customisation (which is a shame since i prefer sass). I really don't want to eject the project either.

**Comment by kamronbatman** [comment]
> @kamronbatman hm, how are you embedding antd in your create-react-app then? afaik antd needs less for customisation (which is a shame since i prefer sass). I really don't want to eject the project either. 

Great question. I ended up using craco and less-loader directly. Then making a less file, importing the antd less files, making my changes, then importing that file manually into the root App.tsx.

**Comment by guoyubo00737** [comment]
I found out that this problem is caused by the structure of the higher version of create-react-app, which may be solved by toggling craco-less and configuring the craco.config.less field. My craco-less version is 2.0.0.
![截屏2022-04-20 10 54 47](https://user-images.githubusercontent.com/43675626/164141053-129d59aa-4d16-410b-bae4-8ae0dce2f72f.png)

**Comment by nerdess** [comment]
looks like https://www.npmjs.com/package/@mrbatman/craco-antd is gone and has been merged into the initial craco-antd packe. so using this package is fine again :)

**Comment by tdevthairun** [comment]
> looks like https://www.npmjs.com/package/@mrbatman/craco-antd is gone and has been merged into the initial craco-antd package. so using this package is fine again :)

it not work for me
